org: kaiznanji
app: serverless
service: creditrewards-backend

frameworkVersion: '3'

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  httpApi:
    cors: true

functions:
  app:
    handler: app/main.handler
    events:
      - http:
          method: get
          path: /
          cors: true
      - http:
          method: post
          path: /rewards
          cors: true
      - http:
          method: get
          path: /rules
          cors: true

plugins:
  - serverless-python-requirements
